INSERT INTO book (title, price, author, image) VALUES ('Our Own Stories: Readings for Cross-Cultural Communication', 25.65, 'Norine Dresser', 'http://test.org/image/9780200000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Sky Begins at Your Feet', 15.69, 'Caryn Mirriam-Goldberg', 'http://test.org/image/9781890000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Hot Biscuits: Eighteen Stories by Women and Men of the Ranching West', 12.95, 'Max Evans', 'http://test.org/image/9780830000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Santa Fe Nativa: A Collection of Nuevomexicano Writing', 15.84, 'Rosalie C. Otero', 'http://test.org/image/9780830000000.png');
INSERT INTO book (title, price, author, image) VALUES ('The Best American Short Plays 2004-2005', 15.83, 'Barbara Parisi', 'http://test.org/image/9781560000000.png');
INSERT INTO book (title, price, author, image) VALUES ('En Otra Voz: Antolog&#237;a de Literatura Hispana de los Estados Unidos', 8.39, 'Nicolas Kanellos', 'http://test.org/image/9781560000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Common Wealth', 33.55, 'Marjorie Maddox', 'http://test.org/image/9780270000000.png');
INSERT INTO book (title, price, author, image) VALUES ('American Satire', 26.44, 'Nicholas Bakalar', 'http://test.org/image/9780450000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Appalachia inside Out, Vol. 2', 17.69, 'Robert J. Higgs', 'http://test.org/image/9780870000000.png');
INSERT INTO book (title, price, author, image) VALUES ('New Stories from the Southwest', 19.22, 'D. Seth Horton', 'http://test.org/image/9780800000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Writing New England: An Anthology from the Puritans to the Present', 1.99, 'Andrew Delbanco', 'http://test.org/image/9780670000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Crazy Woman Creek: Women Rewrite the American West', 9.52, 'Nancy Curtis', 'http://test.org/image/9780620000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Circle of Women: An Anthology of Contemporary Western Women Writers', 19.95, 'Kim Barnes', 'http://test.org/image/9780810000000.png');
INSERT INTO book (title, price, author, image) VALUES ('The Portable Western Reader', 19.24, 'Various', 'http://test.org/image/9780140000000.png');
INSERT INTO book (title, price, author, image) VALUES ('African-American Literature: A Brief Introduction and Anthology', 51.80, 'Al Young', 'http://test.org/image/9780670000000.png');
INSERT INTO book (title, price, author, image) VALUES ('El Coro', 10.34, 'Martin Espada', 'http://test.org/image/9781560000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Off Off Broadway Festival Plays, 34th Series', 8.95, 'Various', 'http://test.org/image/9780570000000.png');
INSERT INTO book (title, price, author, image) VALUES ('American Wits: An Anthology of Light Verse', 19.28, 'VARIOUS', 'http://test.org/image/9781930000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Out on the Porch: An Evocation in Words and Pictures', 1.99, 'Reynolds Price', 'http://test.org/image/9780950000000.png');
INSERT INTO book (title, price, author, image) VALUES ('30 Satires', 15.95, 'Lewis H. Lapham', 'http://test.org/image/9781570000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Literary Mama: Reading for the Maternally Inclined', 10.16, 'Andrea J. Buchanan', 'http://test.org/image/9781580000000.png');
INSERT INTO book (title, price, author, image) VALUES ('In So Many More Words: Arguments and Adventures, Second Edition', 22.00, 'Robert Schmuhl', 'http://test.org/image/9780270000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Georgia Cowboy Poets', 24.17, 'David Fillingim', 'http://test.org/image/9780880000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Decolonial Voices: Chicana and Chicano Cultural Studies in the 21st Century', 23.95, 'Arturo J. Aldama', 'http://test.org/image/9780250000000.png');
INSERT INTO book (title, price, author, image) VALUES ('More Mirth of a Nation: The Best Contemporary Humor', 15.95, 'Michael J. Rosen', 'http://test.org/image/9780060000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Our Own Stories: Readings for Cross-Cultural Communication', 25.65, 'Norine Dresser', 'http://test.org/image/9780200000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Sky Begins at Your Feet', 15.69, 'Caryn Mirriam-Goldberg', 'http://test.org/image/9781890000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Hot Biscuits: Eighteen Stories by Women and Men of the Ranching West', 12.95, 'Max Evans', 'http://test.org/image/9780830000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Santa Fe Nativa: A Collection of Nuevomexicano Writing', 15.84, 'Rosalie C. Otero', 'http://test.org/image/9780830000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_The Best American Short Plays 2004-2005', 15.83, 'Barbara Parisi', 'http://test.org/image/9781560000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_En Otra Voz: Antolog&#237;a de Literatura Hispana de los Estados Unidos', 8.39, 'Nicolas Kanellos', 'http://test.org/image/9781560000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Common Wealth', 33.55, 'Marjorie Maddox', 'http://test.org/image/9780270000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_American Satire', 26.44, 'Nicholas Bakalar', 'http://test.org/image/9780450000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Appalachia inside Out, Vol. 2', 17.69, 'Robert J. Higgs', 'http://test.org/image/9780870000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_New Stories from the Southwest', 19.22, 'D. Seth Horton', 'http://test.org/image/9780800000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Writing New England: An Anthology from the Puritans to the Present', 1.99, 'Andrew Delbanco', 'http://test.org/image/9780670000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Crazy Woman Creek: Women Rewrite the American West', 9.52, 'Nancy Curtis', 'http://test.org/image/9780620000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Circle of Women: An Anthology of Contemporary Western Women Writers', 19.95, 'Kim Barnes', 'http://test.org/image/9780810000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_The Portable Western Reader', 19.24, 'Various', 'http://test.org/image/9780140000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_African-American Literature: A Brief Introduction and Anthology', 51.80, 'Al Young', 'http://test.org/image/9780670000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_El Coro', 10.34, 'Martin Espada', 'http://test.org/image/9781560000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Off Off Broadway Festival Plays, 34th Series', 8.95, 'Various', 'http://test.org/image/9780570000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_American Wits: An Anthology of Light Verse', 19.28, 'VARIOUS', 'http://test.org/image/9781930000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Out on the Porch: An Evocation in Words and Pictures', 1.99, 'Reynolds Price', 'http://test.org/image/9780950000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_30 Satires', 15.95, 'Lewis H. Lapham', 'http://test.org/image/9781570000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Literary Mama: Reading for the Maternally Inclined', 10.16, 'Andrea J. Buchanan', 'http://test.org/image/9781580000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_In So Many More Words: Arguments and Adventures, Second Edition', 22.00, 'Robert Schmuhl', 'http://test.org/image/9780270000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Georgia Cowboy Poets', 24.17, 'David Fillingim', 'http://test.org/image/9780880000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_Decolonial Voices: Chicana and Chicano Cultural Studies in the 21st Century', 23.95, 'Arturo J. Aldama', 'http://test.org/image/9780250000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Another_More Mirth of a Nation: The Best Contemporary Humor', 15.95, 'Michael J. Rosen', 'http://test.org/image/9780060000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Our Own Stories: Readings for Cross-Cultural Communication', 25.65, 'Norine Dresser', 'http://test.org/image/9780200000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Sky Begins at Your Feet', 15.69, 'Caryn Mirriam-Goldberg', 'http://test.org/image/9781890000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Hot Biscuits: Eighteen Stories by Women and Men of the Ranching West', 12.95, 'Max Evans', 'http://test.org/image/9780830000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Santa Fe Nativa: A Collection of Nuevomexicano Writing', 15.84, 'Rosalie C. Otero', 'http://test.org/image/9780830000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_The Best American Short Plays 2004-2005', 15.83, 'Barbara Parisi', 'http://test.org/image/9781560000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_En Otra Voz: Antolog&#237;a de Literatura Hispana de los Estados Unidos', 8.39, 'Nicolas Kanellos', 'http://test.org/image/9781560000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Common Wealth', 33.55, 'Marjorie Maddox', 'http://test.org/image/9780270000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_American Satire', 26.44, 'Nicholas Bakalar', 'http://test.org/image/9780450000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Appalachia inside Out, Vol. 2', 17.69, 'Robert J. Higgs', 'http://test.org/image/9780870000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_New Stories from the Southwest', 19.22, 'D. Seth Horton', 'http://test.org/image/9780800000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Writing New England: An Anthology from the Puritans to the Present', 1.99, 'Andrew Delbanco', 'http://test.org/image/9780670000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Crazy Woman Creek: Women Rewrite the American West', 9.52, 'Nancy Curtis', 'http://test.org/image/9780620000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Circle of Women: An Anthology of Contemporary Western Women Writers', 19.95, 'Kim Barnes', 'http://test.org/image/9780810000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_The Portable Western Reader', 19.24, 'Various', 'http://test.org/image/9780140000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_African-American Literature: A Brief Introduction and Anthology', 51.80, 'Al Young', 'http://test.org/image/9780670000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_El Coro', 10.34, 'Martin Espada', 'http://test.org/image/9781560000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Off Off Broadway Festival Plays, 34th Series', 8.95, 'Various', 'http://test.org/image/9780570000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_American Wits: An Anthology of Light Verse', 19.28, 'VARIOUS', 'http://test.org/image/9781930000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Out on the Porch: An Evocation in Words and Pictures', 1.99, 'Reynolds Price', 'http://test.org/image/9780950000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_30 Satires', 15.95, 'Lewis H. Lapham', 'http://test.org/image/9781570000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Literary Mama: Reading for the Maternally Inclined', 10.16, 'Andrea J. Buchanan', 'http://test.org/image/9781580000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_In So Many More Words: Arguments and Adventures, Second Edition', 22.00, 'Robert Schmuhl', 'http://test.org/image/9780270000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Georgia Cowboy Poets', 24.17, 'David Fillingim', 'http://test.org/image/9780880000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_Decolonial Voices: Chicana and Chicano Cultural Studies in the 21st Century', 23.95, 'Arturo J. Aldama', 'http://test.org/image/9780250000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_More Mirth of a Nation: The Best Contemporary Humor', 15.95, 'Michael J. Rosen', 'http://test.org/image/9780060000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Our Own Stories: Readings for Cross-Cultural Communication', 25.65, 'Norine Dresser', 'http://test.org/image/9780200000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Sky Begins at Your Feet', 15.69, 'Caryn Mirriam-Goldberg', 'http://test.org/image/9781890000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Hot Biscuits: Eighteen Stories by Women and Men of the Ranching West', 12.95, 'Max Evans', 'http://test.org/image/9780830000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Santa Fe Nativa: A Collection of Nuevomexicano Writing', 15.84, 'Rosalie C. Otero', 'http://test.org/image/9780830000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_The Best American Short Plays 2004-2005', 15.83, 'Barbara Parisi', 'http://test.org/image/9781560000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_En Otra Voz: Antolog&#237;a de Literatura Hispana de los Estados Unidos', 8.39, 'Nicolas Kanellos', 'http://test.org/image/9781560000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Common Wealth', 33.55, 'Marjorie Maddox', 'http://test.org/image/9780270000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_American Satire', 26.44, 'Nicholas Bakalar', 'http://test.org/image/9780450000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Appalachia inside Out, Vol. 2', 17.69, 'Robert J. Higgs', 'http://test.org/image/9780870000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_New Stories from the Southwest', 19.22, 'D. Seth Horton', 'http://test.org/image/9780800000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Writing New England: An Anthology from the Puritans to the Present', 1.99, 'Andrew Delbanco', 'http://test.org/image/9780670000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Crazy Woman Creek: Women Rewrite the American West', 9.52, 'Nancy Curtis', 'http://test.org/image/9780620000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Circle of Women: An Anthology of Contemporary Western Women Writers', 19.95, 'Kim Barnes', 'http://test.org/image/9780810000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_The Portable Western Reader', 19.24, 'Various', 'http://test.org/image/9780140000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_African-American Literature: A Brief Introduction and Anthology', 51.80, 'Al Young', 'http://test.org/image/9780670000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_El Coro', 10.34, 'Martin Espada', 'http://test.org/image/9781560000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Off Off Broadway Festival Plays, 34th Series', 8.95, 'Various', 'http://test.org/image/9780570000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_American Wits: An Anthology of Light Verse', 19.28, 'VARIOUS', 'http://test.org/image/9781930000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Out on the Porch: An Evocation in Words and Pictures', 1.99, 'Reynolds Price', 'http://test.org/image/9780950000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_30 Satires', 15.95, 'Lewis H. Lapham', 'http://test.org/image/9781570000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Literary Mama: Reading for the Maternally Inclined', 10.16, 'Andrea J. Buchanan', 'http://test.org/image/9781580000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_In So Many More Words: Arguments and Adventures, Second Edition', 22.00, 'Robert Schmuhl', 'http://test.org/image/9780270000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Georgia Cowboy Poets', 24.17, 'David Fillingim', 'http://test.org/image/9780880000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_Decolonial Voices: Chicana and Chicano Cultural Studies in the 21st Century', 23.95, 'Arturo J. Aldama', 'http://test.org/image/9780250000000.png');
INSERT INTO book (title, price, author, image) VALUES ('Yet_Another_book_More Mirth of a Nation: The Best Contemporary Humor', 15.95, 'Michael J. Rosen', 'http://test.org/image/9780060000000.png');

